name: volume
description: Volume plugin to control device VOLUME (Android only). Pull request for IOS implementation is welcome. 
version: 0.1.0
author: Aman Malhotra<official.aman18@gmail.com>
homepage: https://github.com/aman-malhotra-1999/Volume_Flutter.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.volume
    pluginClass: VolumePlugin
